# Site settings
title: Mahmood's Personal Website
description: This is my portfolio and was a fun project
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mahmood Sales
user_description: I am a junior in computer science and am looking for a job in the field. I am passionate about technology and am eager to further my knowledge and experience. I have experience in coding in C++ and Python, as well as a strong understanding of software engineering and web development. I am looking for positions such as software engineer, software developer, front end developer, and web developer. I am excited to explore the opportunities in the computer science field and am eager to utilize my knowledge and skills to make a difference.
user_title: Software Developer
email: sales@usf.edu
linkedin_username: mahmood-sales  # New entry for LinkedIn
github_username:  makdoodie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
